// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import "reflect"

// Admin represents a row from 'public.admins'.
type Admin struct {
	ID       int64  `db:"id" json:"id"`               // id
	FullName string `db:"full_name" json:"full_name"` // full_name
	Phone    string `db:"phone" json:"phone"`         // phone
	Tg       string `db:"tg" json:"tg"`               // tg
}

// zeroAdmin zero value of dto
var zeroAdmin = Admin{}

func (t Admin) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroAdmin)
}
