// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"fmt"
	"reflect"
	"strings"
)

// AssistantTg represents a row from 'public.assistant_tgs'.
type AssistantTg struct {
	ID           int64            `db:"id" json:"id"`                       // id bigint
	UserID       sql.NullInt64    `db:"user_id" json:"user_id"`             // user_id bigint
	AvailableTgs []sql.NullString `db:"available_tgs" json:"available_tgs"` // available_tgs text[]
}

// zeroAssistantTg zero value of dto
var zeroAssistantTg = AssistantTg{}

// Constants that should be used when building where statements
const (
	Alias_AssistantTg              = "at"
	Table_AssistantTg_With_Alias   = "assistant_tgs AS at"
	Table_AssistantTg              = "assistant_tgs"
	Field_AssistantTg_ID           = "id"
	Field_AssistantTg_UserID       = "user_id"
	Field_AssistantTg_AvailableTgs = "available_tgs"
)

func (t AssistantTg) SelectColumnsWithCoalesce() []string {
	return []string{
		fmt.Sprintf("COALESCE(at.id, %v) as id", zeroAssistantTg.ID),
		"at.user_id",
		fmt.Sprintf("COALESCE(at.available_tgs, %v) as available_tgs", zeroAssistantTg.AvailableTgs),
	}
}

func (t AssistantTg) SelectColumns() []string {
	return []string{
		"at.id",
		"at.user_id",
		"at.available_tgs",
	}
}

func (t AssistantTg) Columns(without ...string) []string {
	var str = "id, user_id, available_tgs"
	for _, exc := range without {
		str = strings.Replace(str+", ", exc+", ", "", 1)
	}
	return strings.Split(strings.TrimRight(str, ", "), ", ")
}

func (t AssistantTg) WithTable(col string) string {
	return fmt.Sprintf("at.%s", col)
}

func (t AssistantTg) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroAssistantTg)
}

func (t AssistantTg) Join(rightColumnTable string, leftColumnTable string) string {
	return fmt.Sprintf("assistant_tgs AS at ON at.%s = %s", rightColumnTable, leftColumnTable)
}

func (t *AssistantTg) ToMap() map[string]interface{} {
	return map[string]interface{}{
		"id":            t.ID,
		"user_id":       t.UserID,
		"available_tgs": t.AvailableTgs,
	}
}

func (t *AssistantTg) Values(colNames ...string) (vals []interface{}) {
	m := t.ToMap()

	for _, v := range colNames {
		vals = append(vals, m[v])
	}

	return vals
}
