// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"fmt"
	"reflect"
	"strings"

	"github.com/lib/pq"
)

// NotificationHistory represents a row from 'public.notification_history'.
type NotificationHistory struct {
	ID         int64         `db:"id" json:"id"`                     // id bigint
	CreatedAt  pq.NullTime   `db:"created_at" json:"created_at"`     // created_at timestamp without time zone
	ParentTgID sql.NullInt64 `db:"parent_tg_id" json:"parent_tg_id"` // parent_tg_id bigint
	UserID     sql.NullInt64 `db:"user_id" json:"user_id"`           // user_id bigint
}

// zeroNotificationHistory zero value of dto
var zeroNotificationHistory = NotificationHistory{}

// Constants that should be used when building where statements
const (
	Alias_NotificationHistory            = "nh"
	Table_NotificationHistory_With_Alias = "notification_history AS nh"
	Table_NotificationHistory            = "notification_history"
	Field_NotificationHistory_ID         = "id"
	Field_NotificationHistory_CreatedAt  = "created_at"
	Field_NotificationHistory_ParentTgID = "parent_tg_id"
	Field_NotificationHistory_UserID     = "user_id"
)

func (t NotificationHistory) SelectColumnsWithCoalesce() []string {
	return []string{
		fmt.Sprintf("COALESCE(nh.id, %v) as id", zeroNotificationHistory.ID),
		"nh.created_at",
		"nh.parent_tg_id",
		"nh.user_id",
	}
}

func (t NotificationHistory) SelectColumns() []string {
	return []string{
		"nh.id",
		"nh.created_at",
		"nh.parent_tg_id",
		"nh.user_id",
	}
}

func (t NotificationHistory) Columns(without ...string) []string {
	var str = "id, created_at, parent_tg_id, user_id"
	for _, exc := range without {
		str = strings.Replace(str+", ", exc+", ", "", 1)
	}
	return strings.Split(strings.TrimRight(str, ", "), ", ")
}

func (t NotificationHistory) WithTable(col string) string {
	return fmt.Sprintf("nh.%s", col)
}

func (t NotificationHistory) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroNotificationHistory)
}

func (t NotificationHistory) Join(rightColumnTable string, leftColumnTable string) string {
	return fmt.Sprintf("notification_history AS nh ON nh.%s = %s", rightColumnTable, leftColumnTable)
}

func (t *NotificationHistory) ToMap() map[string]interface{} {
	return map[string]interface{}{
		"id":           t.ID,
		"created_at":   t.CreatedAt,
		"parent_tg_id": t.ParentTgID,
		"user_id":      t.UserID,
	}
}

func (t *NotificationHistory) Values(colNames ...string) (vals []interface{}) {
	m := t.ToMap()

	for _, v := range colNames {
		vals = append(vals, m[v])
	}

	return vals
}
