// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import "reflect"

// Student represents a row from 'public.students'.
type Student struct {
	ID              int64  `db:"id" json:"id"`                               // id
	FirstName       string `db:"first_name" json:"first_name"`               // first_name
	LastName        string `db:"last_name" json:"last_name"`                 // last_name
	MiddleName      string `db:"middle_name" json:"middle_name"`             // middle_name
	Phone           string `db:"phone" json:"phone"`                         // phone
	Tg              string `db:"tg" json:"tg"`                               // tg
	CostPerHour     string `db:"cost_per_hour" json:"cost_per_hour"`         // cost_per_hour
	SubjectID       int64  `db:"subject_id" json:"subject_id"`               // subject_id
	TutorID         int64  `db:"tutor_id" json:"tutor_id"`                   // tutor_id
	IsFinishedTrial bool   `db:"is_finished_trial" json:"is_finished_trial"` // is_finished_trial
	ParentFullName  string `db:"parent_full_name" json:"parent_full_name"`   // parent_full_name
	ParentPhone     string `db:"parent_phone" json:"parent_phone"`           // parent_phone
	ParentTg        string `db:"parent_tg" json:"parent_tg"`                 // parent_tg
}

// zeroStudent zero value of dto
var zeroStudent = Student{}

func (t Student) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroStudent)
}
