// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import "reflect"

// Subject represents a row from 'public.subjects'.
type Subject struct {
	ID   int64  `db:"id" json:"id"`     // id
	Name string `db:"name" json:"name"` // name
}

// zeroSubject zero value of dto
var zeroSubject = Subject{}

func (t Subject) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroSubject)
}
