// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"fmt"
	"reflect"
	"strings"
)

// TgAdminsUsername represents a row from 'public.tg_admins_usernames'.
type TgAdminsUsername struct {
	ID      int64  `db:"id" json:"id"`             // id bigint
	AdminID int64  `db:"admin_id" json:"admin_id"` // admin_id bigint
	Name    string `db:"name" json:"name"`         // name text
}

// zeroTgAdminsUsername zero value of dto
var zeroTgAdminsUsername = TgAdminsUsername{}

// Constants that should be used when building where statements
const (
	Alias_TgAdminsUsername            = "tau"
	Table_TgAdminsUsername_With_Alias = "tg_admins_usernames AS tau"
	Table_TgAdminsUsername            = "tg_admins_usernames"
	Field_TgAdminsUsername_ID         = "id"
	Field_TgAdminsUsername_AdminID    = "admin_id"
	Field_TgAdminsUsername_Name       = "name"
)

func (t TgAdminsUsername) SelectColumnsWithCoalesce() []string {
	return []string{
		fmt.Sprintf("COALESCE(tau.id, %v) as id", zeroTgAdminsUsername.ID),
		fmt.Sprintf("COALESCE(tau.admin_id, %v) as admin_id", zeroTgAdminsUsername.AdminID),
		fmt.Sprintf("COALESCE(tau.name, '%v') as name", zeroTgAdminsUsername.Name),
	}
}

func (t TgAdminsUsername) SelectColumns() []string {
	return []string{
		"tau.id",
		"tau.admin_id",
		"tau.name",
	}
}

func (t TgAdminsUsername) Columns(without ...string) []string {
	var str = "id, admin_id, name"
	for _, exc := range without {
		str = strings.Replace(str+", ", exc+", ", "", 1)
	}
	return strings.Split(strings.TrimRight(str, ", "), ", ")
}

func (t TgAdminsUsername) WithTable(col string) string {
	return fmt.Sprintf("tau.%s", col)
}

func (t TgAdminsUsername) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroTgAdminsUsername)
}

func (t TgAdminsUsername) Join(rightColumnTable string, leftColumnTable string) string {
	return fmt.Sprintf("tg_admins_usernames AS tau ON tau.%s = %s", rightColumnTable, leftColumnTable)
}

func (t *TgAdminsUsername) ToMap() map[string]interface{} {
	return map[string]interface{}{
		"id":       t.ID,
		"admin_id": t.AdminID,
		"name":     t.Name,
	}
}

func (t *TgAdminsUsername) Values(colNames ...string) (vals []interface{}) {
	m := t.ToMap()

	for _, v := range colNames {
		vals = append(vals, m[v])
	}

	return vals
}
