// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"fmt"
	"reflect"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
)

// Tutor represents a row from 'public.tutors'.
type Tutor struct {
	ID              int64          `db:"id" json:"id"`                               // id bigint
	CostPerHour     pgtype.Numeric `db:"cost_per_hour" json:"cost_per_hour"`         // cost_per_hour numeric
	SubjectID       int64          `db:"subject_id" json:"subject_id"`               // subject_id bigint
	AdminID         int64          `db:"admin_id" json:"admin_id"`                   // admin_id bigint
	IsArchive       sql.NullBool   `db:"is_archive" json:"is_archive"`               // is_archive bool
	TgAdminUsername sql.NullString `db:"tg_admin_username" json:"tg_admin_username"` // tg_admin_username text
}

// zeroTutor zero value of dto
var zeroTutor = Tutor{}

// Constants that should be used when building where statements
const (
	Alias_Tutor                 = "t"
	Table_Tutor_With_Alias      = "tutors AS t"
	Table_Tutor                 = "tutors"
	Field_Tutor_ID              = "id"
	Field_Tutor_CostPerHour     = "cost_per_hour"
	Field_Tutor_SubjectID       = "subject_id"
	Field_Tutor_AdminID         = "admin_id"
	Field_Tutor_IsArchive       = "is_archive"
	Field_Tutor_TgAdminUsername = "tg_admin_username"
)

func (t Tutor) SelectColumnsWithCoalesce() []string {
	return []string{
		fmt.Sprintf("COALESCE(t.id, %v) as id", zeroTutor.ID),
		fmt.Sprintf("COALESCE(t.cost_per_hour, %v) as cost_per_hour", zeroTutor.CostPerHour),
		fmt.Sprintf("COALESCE(t.subject_id, %v) as subject_id", zeroTutor.SubjectID),
		fmt.Sprintf("COALESCE(t.admin_id, %v) as admin_id", zeroTutor.AdminID),
		"t.is_archive",
		"t.tg_admin_username",
	}
}

func (t Tutor) SelectColumns() []string {
	return []string{
		"t.id",
		"t.cost_per_hour",
		"t.subject_id",
		"t.admin_id",
		"t.is_archive",
		"t.tg_admin_username",
	}
}

func (t Tutor) Columns(without ...string) []string {
	var str = "id, cost_per_hour, subject_id, admin_id, is_archive, tg_admin_username"
	for _, exc := range without {
		str = strings.Replace(str+", ", exc+", ", "", 1)
	}
	return strings.Split(strings.TrimRight(str, ", "), ", ")
}

func (t Tutor) WithTable(col string) string {
	return fmt.Sprintf("t.%s", col)
}

func (t Tutor) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroTutor)
}

func (t Tutor) Join(rightColumnTable string, leftColumnTable string) string {
	return fmt.Sprintf("tutors AS t ON t.%s = %s", rightColumnTable, leftColumnTable)
}

func (t *Tutor) ToMap() map[string]interface{} {
	return map[string]interface{}{
		"id":                t.ID,
		"cost_per_hour":     t.CostPerHour,
		"subject_id":        t.SubjectID,
		"admin_id":          t.AdminID,
		"is_archive":        t.IsArchive,
		"tg_admin_username": t.TgAdminUsername,
	}
}

func (t *Tutor) Values(colNames ...string) (vals []interface{}) {
	m := t.ToMap()

	for _, v := range colNames {
		vals = append(vals, m[v])
	}

	return vals
}
