// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import "reflect"

// Wallet represents a row from 'public.wallet'.
type Wallet struct {
	ID        int64  `db:"id" json:"id"`                 // id
	StudentID int64  `db:"student_id" json:"student_id"` // student_id
	Balance   string `db:"balance" json:"balance"`       // balance
}

// zeroWallet zero value of dto
var zeroWallet = Wallet{}

func (t Wallet) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroWallet)
}
